dist: xenial
sudo: required
language: python
services:
- docker
python:
- 3.7
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
  - DOCKER_REPO: akariv/dgp-server
  - secure: CTKen+8QFFHqbSvtpHcYnsfgTskWMGJ3oxiQ50gzxiE9MkstSLXjcskg4c373MY/ZYvsqy8fznuKYLOoJiwhgVrc1vCt1BRJTMtCu8jDtQoPRsoYrtRX5wvymDq+/RFAKA7U9a1bv3J5dlJzo7aseEq3sRjEHfAukXq6Oi4KlA9GJXALih6EN/iozrckgFXDQKKFSNWJJ2/qPMqWftU7+VsBNjTmF0dOYT/BOuxVw5f/WWJZsinDJEfYDxpg/fhW+jzwonPjvsGDUKmV4MPTWwdCP/cZzgAI+N6wzgyKkGli6+FtHyAw91r+a7n8dk01uucJqMGxHkqBfjXvw85SntYnGADwAJO6rL9P6wf05LFXFRjDEM76G3xij9mcyVC8+5+GoP0ICsG/QRZ05g8T9xrv+PBEsiuLLpNfzwIlX0wkOt6U0TPubId4rQ+FeKozRMVhYlpCGNCKbFCKJEFXEBaqJrBttP8enR2kq1NkMtSll0rg2CFe5hBx3USp0jwTvp9y6JBCkzIAJ8nOxYe/lr3MgTlfIiKdHaaJo2QzMVEXaj5uOOK2aOppoOwiNwMLTj6t34uOXnBqbs/tMUocqFFmWzifWaC2M1y8niY6GjQDX2Ft1Vm0eB66Cz4z9I71iAqclHJ2tPLyXuoLqMbNtfZSJ0yNlzuTHKakRl249J8=
  - secure: DapyK3+vaKcAGh+ih70+NKRG8rCU5vZOVorrn8ub30k1El3pzCoHqP0yA30BWYTp23GpxJSZRydFOTUECGphr20qpvaAj3b99CdShucYefkfaovePD38W9kI3y972SFgsekwyAWACsO2Ev32kbuzRGzPRxxHh1iF5ipcsSO2c0AFYG6RjKDATw4vNmjhCHvHqjrR2oyl2mA8+agbEXZsn2alukKpyrPALGdeArV2gwJrh4lumsfrPaJSwyRJYijgx+aOi3arSbU+Dpue4gyMhF4xP7fAg8ZM7PaGZBlN9hapvCFRfEa0EABS5XgZLFpCE3Cwjbag5zqnaBkEp8b7IZ54Z+BoMh0MSF44iqRa8jXJKVboeqWBWbOIMz3v3WqKQd6oHzoigC7zkQFZZ0bZiUc58CczHG57zELgUzp2/tlSVei0X3YH+pT8iG/3ljujwQNnjad0Fs9qG7ufzKte+QawFF1+1yeqP72m2srCqUHAmXActL9zHJm8criww9YiADzTdupeLKDP8Kll128Pon88Px+VqrFQCU6ijlATnvYk1atERcmM5N77t6ka5RBx/CaDa8MmcE4S4TCvKWnjwHBfEX/05PSH8vbM3Meip+cN33Z0xGUiimzb9nA2pGM22l//Tg5+8cfaoRiWohkPhk0OjG2jKBwYNwt8SWI6440=
script:
- docker build -t $DOCKER_REPO:latest
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
